all:
	cd agent_plan && make 
	cd event_distributions && make
	cd emachine && make
	
clean:
	cd agent_plan && make clean
	cd event_distributions && make clean
	cd mentalplan  && make clean
	cd agent && make clean
	cd emachine && make clean

debug:
	cd agent_plan && make debug
	cd event_distributions && make debug
	cd mentalplan && make debug
	cd agent && make debug
	cd emachine && make debug
